name: Arduino controller

on:
  push:
    branches: [main]
    paths: ["arduino/**", ".github/workflows/arduino.yml"]
  pull_request:
    paths: ["arduino/**", ".github/workflows/arduino.yml"]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            - arduino
          libraries: |
            - name: Servo